# Compose is a tool for defining / running multi-container docker apps. YAML file confitures apps services
# docker-compose up starts and runs the entire app
version: "3"
services:
# node app running on port 3001
  postgres:
    container_name: postgres
    image: postgres:latest
    # volumes:
    #   - data-volume:/data/db
    # ports:
    #   - "27017:27017"
    # command: mongod --bind_ip 127.0.0.1
    command: postgres --port 5432
    ports:
    - '5432:5432'
    # command: mongod --bind_ip 0.0.0.0
    # command: ["--bind_ip_all"]
  web:
    # volumes:
    #   - data-volume:/data/db
    # container_name: reviews_component_web
    image: node:latest
    build: .
    # RUN npm run seed
    # command: sh -c 'npm install; npm run seed; npm start'
    command: sudo "npm run seed; npm start"
    ports:
      - "3000:3000"
      # - "80:3001"
    links:
      - postgres
  #Below used to attempt to seed from another container. this linked to that file dir
  # db:
  #   build: ./database
# Persist data at below dedicated dir
# volumes:
#   data-volume: