// // const db = require('./index.js');


// const getRandomNum = () => {
//   return Math.floor(Math.random() * 100);
// };

const data = [
  `('ABC Jogger', 'Mens', 128, 12, 'Anti Ball Crushing', 'Four Way Stretch Warpstreme Fabric', 'Baggy', 'True Navy', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/ABC+Jogger+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/ABC+Jogger+Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/ABC+Jogger+Olive+Green+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/ABC+Jogger+Olive+Green+2.webp')`,
  `('City Sweat Jogger', 'Mens', 118, 12, 'On the Move', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit', 'Heather Allover Sea Salt Light Cast', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heather+Allover+Sea+Salt+Light+Cast.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/City+Sweat+Jogger+Light+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/City+Sweat+Jogger+Light+Grey+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/City+Sweat+Jogger+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/City+Sweat+Jogger+Black+2.webp')`,
  `('Surge Jogger', 'Mens', 118, 12, 'Running', 'Four Way Stretch', 'Roomy', 'Mach Blue', 'Vapor', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Mach+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Surge+Jogger+Mach+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Surge+Jogger+Mach+Blue+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Surge+Jogger+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Surge+Jogger+Vapor+2.webp')`,
  `('Textured Tech Jogger', 'Mens', 128, 12, 'Casual', 'Sweat-Wicking Fabric', 'Loose',  'Cadet Blue', 'Graphite Grey', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cadet+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Texured+Tech+Jogger+Cadet+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Texured+Tech+Jogger+Cadet+Blue+2.webp','https://lulupics.s3.us-east-2.amazonaws.com/Texured+Tech+Jogger+2.webp','https://lulupics.s3.us-east-2.amazonaws.com/Texured+Tech+Jogger+Grey+1.webp')`,
  `('Commission Short', 'Mens', 88, 12, 'Comfort', 'Four Way Stretch, Warpstreme Fabric', 'Classic Fit',  'Black', 'Grey Sage', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Grey+Sage.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Black+2.webp','https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Grey+Sage+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Grey+Sage+2.webp')`,
  `('T.H.E. Short Linerless', 'Mens', 68, 12, 'Comfort', 'Four Way Stretch, Warpstreme Fabric', 'Classic Fit', 'Cadet Blue', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cadet+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/T.H.E.+Short+Linerless+Cadet+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/T.H.E.+Short+Linerless+Cadet+Blue+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/T.H.E.+Short+Linerless+Heather+Coal+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/T.H.E.+Short+Linerless+Heather+Coal+2.webp')`,
  `('Surge Short Liner', 'Mens', 68, 12, 'Lightweight', 'Four Way Stretch', 'Classic Fit, 6 inch Inseam',  'Heather Allover Iron Blue True Navy', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Harbor+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shorts','https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Surge+Short++Heather+Allover+Iron+Blue+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Surge+Short++Heather+Allover+Iron+Blue+True+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/surge+short++Heather+Allover+Deep+Coal+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/surge+short++Heather+Allover+Deep+Coal+Black+2.webp')`,
  `('City Sweat Short 9in', 'Mens',  68, 12, 'Training and On the Move', 'Soft, Stretch French Terry Fabric', 'Classic Fit', 'True Navy', 'Graphite Grey',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/City+Sweat+Short+Heathered+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/City+Sweat+Short+Heathered+True+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/City+Sweat+Short+Heather+grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/City+Sweat+Short++Heathered+Core+Medium+Grey+1.webp')`,
  `('Current State Board Short 9in', 'Mens', 98, 12, 'Training and Swim', 'Lightweight, Four Way Stretch Fabric', '9in Inseam',  'Black', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Current+State+Board+Short+black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Current+State+Board+Short+black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Current+State+Board+Short+blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Current+State+Board+Short+blue+2.webp')`,
  `('At Ease Short 7in', 'Mens', 78, 12, 'Training and On the Move', 'Soft, Stretch French Terry Fabric', '7in Inseam', 'Black', 'Heather Allover Sea Salt Light Cast', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heather+Allover+Iron+Blue+True+Navy.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/At+Ease+Short++Heathered+Black%3ABlack+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/At+Ease+Short++Heathered+Black%3ABlack+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/At+Ease+Short++Heathered+Melody+Light+Grey%3ABlack+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/At+Ease+Short++Heathered+Melody+Light+Grey%3ABlack+2.webp')`,
  `('Airing Easy Short Sleeve Shirt', 'Mens', 98, 12, 'On the Move', 'Breathable, Swift Mesh Fabric', 'Classic Fit',  'Vapor', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp','Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Airing+Easy+Short+Sleeve+Shirt+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Airing+Easy+Short+Sleeve+Shirt+Vapor+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Airing+Easy+Short+Sleeve+Shirt+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Airing+Easy+Short+Sleeve+Shirt+Black+2.webp')`,
  `('Commission Short Sleeve Shirt', 'Mens', 98, 12, 'On the Move', 'Sweat-wicking Fabric soft, Cottony feel', 'Classic Fit', 'Harbor Blue', 'White', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Harbor+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Sleeve+Shirt+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Sleeve+Shirt+Blue+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Sleeve+Shirt+White+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Short+Sleeve+Shirt+White+2.webp')`,
  `('Commission Long Sleeve Shirt', 'Mens', 108, 12, 'On the Move', 'Sweat-wicking Fabric soft, Cottony feel', 'Classic Fit', 'Graphite Grey', 'White', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Long+Sleeve+Shirt+Graphite+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Long+Sleeve+Shirt+Graphite+Grey+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Long+Sleeve+Shirt+White+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Commission+Long+Sleeve+Shirt+White+2.webp')`,
  `('Down to the Wire Long Sleeve Shirt', 'Mens', 108, 12, 'On the Move', 'Anti-Stink, Technical Cotton Fabric', 'Classic Fit', 'Heathered Oasis Blue', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heathered+Oasis+Blue.webp',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+Heathered+Oasis+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+Heathered+Oasis+Blue+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+True+Navy+2.webp')`,
  `('Street Lite Short Sleeve Shirt', 'Mens', 108, 12, 'On the Move', 'Two-Way Stretch Fabric', 'Classic Fit', 'Vapor', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Street+Lite+Short+Sleeve+Shirt+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Street+Lite+Short+Sleeve+Shirt+Vapor+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Street+Lite+Short+Sleeve+Shirt+Dark+Olive+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Street+Lite+Short+Sleeve+Shirt+Dark+Olive+2.webp')`,
  `('Down to the Wire Short Sleeve Shirt', 'Mens', 98, 12, 'On the Move', 'Anti-Stink, Technical Cotton Fabric', 'Classic Fit', 'Heathered Oasis Blue', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heathered+Oasis+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+Heathered+Oasis+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+Heathered+Oasis+Blue+2.webp','https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Short+Sleeve+Shirt+True+Navy+2.webp')`,
  `('Down to the Wire Long Sleeve Shirt', 'Mens', 108, 12, 'On the Move', 'Anti-Stink, Technical Cotton Fabric', 'Classic Fit',  'Heathered Oasis Blue', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heathered+Oasis+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Long+Sleeve+Shirt+Heathered+Oasis+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Long+Sleeve+Shirt+Heathered+Oasis+Blue+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Long+Sleeve+Shirt+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Down+to+the+Wire+Long+Sleeve+Shirt+True+Navy+2.webp')`,
  `('Drivers Coat', 'Mens', 248, 12, 'On the Move', 'DWR-Treated Fabric', 'Everyday wear',  'Black', 'Frontier', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Frontier.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Drivers+Coat+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Drivers+Coat+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Drivers+Coat+Frontier+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Drivers+Coat+Frontier+2.webp')`,
  `('Warp Lite Jacket Packable', 'Mens', 148, 12, 'Training', 'Water-Repellent, Swift Fabric', 'Everyday wear',  'Vapor', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Warp+Lite+Jacket+Packable+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Warp+Lite+Jacket+Packable+Vapor+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Warp+Lite+Jacket+Packable+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Warp+Lite+Jacket+Packable+Black+2.webp')`,
  `('Storm Field Jacket', 'Mens', 298, 12, 'On the Move', 'Waterproof, Glyde Fabric', 'Everyday wear', 'Black', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp',  'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Storm+Field+Jacket+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Storm+Field+Jacket+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Storm+Field+Jacket+Dark+Olive+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Storm+Field+Jacket+Dark+Olive+2.webp')`,
  `('Active Jacket', 'Mens', 118, 12, 'Training', 'DWR-Treated Fabric', 'Everyday wear', 'Black', 'White', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Active+Jacket+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Active+Jacket+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Active+Jacket+White+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Active+Jacket+White+2.webp')`,
  `('Sojourn Jacket', 'Mens', 128, 12, 'On the Move', 'Four Way Stretch, Warpstreme Fabric', 'Everyday wear', 'Black', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sojourn+Jacket+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sojourn+Jacket+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sojourn+Jacket+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sojourn+Jacket+True+Navy+2.webp')`,
  `('Down For It All Jacket', 'Mens', 198, 12, 'On the Move', 'Water-Repellent, Glyde Fabric', 'Everyday wear', 'Black', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Down+For+It+All+Jacket+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Down+For+It+All+Jacket+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Down+For+It+All+Jacket+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Down+For+It+All+Jacket+True+Navy+2.webp')`,
  `('Outpour Shell', 'Mens', 248, 12, 'On the Move', 'DWR-Treated Fabric', 'Everyday wear', 'Lunar Rock', 'Frontier', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Lunar+Rock.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Frontier.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Outpour+Shell+Lunar+Rock+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Outpour+Shell+Lunar+Rock+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Outpour+Shell+Frontier+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Outpour+Shell+Frontier+2.webp')`,
  `('Sky Loft Jacket', 'Mens', 119, 12, 'On the Move', 'Water-Resistant, Glyde Fabric', 'Classic Fit', 'Black', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sky+Loft+Jacket+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sky+Loft+Jacket+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sky+Loft+Jacket+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Sky+Loft+Jacket+True+Navy+2.webp')`,
  `('Parkway Shirt Jacket', 'Mens', 198, 12, 'On the Move', 'Water-Repellent Fabric', 'Classic Fit', 'Black', 'Frontier', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Frontier.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Parkway+Shirt+Jacket+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Parkway+Shirt+Jacket+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Parkway+Shirt+Jacket+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Jackets/Parkway+Shirt+Jacket+True+Navy+2.webp')`,
  `('City Sweat Crew', 'Mens', 148, 12, 'Training', 'Soft, Stretch French Terry Fabric', 'Classic Fit', 'Black', 'Vapor', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Crew+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Crew+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Crew+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Crew+Vapor+2.webp')`,
  `('Breaking Bounds Sleeveless Hoodie', 'Mens', 128, 12, 'On the Move', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit', 'Cadet Blue', 'Graphite Grey', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cadet+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp','Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Breaking+Bounds+Sleeveless+Hoodie+Cadet+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Breaking+Bounds+Sleeveless+Hoodie+Cadet+Blue+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Breaking+Bounds+Sleeveless+Hoodie+Graphite+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Breaking+Bounds+Sleeveless+Hoodie+Graphite+Grey+2.webp')`,
  `('City Sweat Pullover Hoodie French Terry', 'Mens', 118, 12, 'On the Move', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit', 'Lunar Rock', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Lunar+Rock.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Pullover+Hoodie+Lunar+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Pullover+Hoodie+Lunar+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Pullover+Hoodie+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Pullover+Hoodie+Black+2.webp')`,
  `('City Sweat Zip Hoodie French Terry', 'Mens', 128, 12, 'Running and Training', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit', 'Lunar Rock', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Lunar+Rock.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Zip+Hoodie+Lunar+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Zip+Hoodie+Lunar+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Zip+Hoodie+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/City+Sweat+Zip+Hoodie+Black+2.webp')`,
  `('Metal Vent Tech Hoodie 2.0', 'Mens', 98, 12, 'Training', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit', 'Slate', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Slate.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Metal+Vent+Tech+Hoodie+2.0+Slate+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Metal+Vent+Tech+Hoodie+2.0+Slate+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Metal+Vent+Tech+Hoodie+2.0+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Metal+Vent+Tech+Hoodie+2.0+True+Navy+2.webp')`,
  `('Fresh Form Hoodie', 'Mens', 108, 12, 'On the Move', 'Lightweight, Rulu Fabric', 'Classic Fit', 'True Navy', 'Graphite Grey', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Fresh+Form+Hoodie+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Fresh+Form+Hoodie+Vapor+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Fresh+Form+Hoodie+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Fresh+Form+Hoodie+Grey+2.webp')`,
  `('Engineered Warmth Jacket', 'Mens', 148, 12, 'On the Move', 'Lightweight, Rulu Fabric', 'Relaxed Fit', 'Dark Olive', 'Graphite Grey', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Engineered+Warmth+Jacket+Dark+Olive+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Engineered+Warmth+Jacket+Dark+Olive+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Engineered+Warmth+Jacket+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Engineered+Warmth+Jacket+Grey+2.webp')`,
  `('Surge Warm Full Zip', 'Mens', 118, 12, 'Running and Training', 'Soft, Stretch French Terry Fabric', 'Classic Fit', 'Graphite Grey', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Full+Zip+Heathered+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Full+Zip+Heathered+Grey+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Full+Zip+Heathered+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Full+Zip+Heathered+True+Navy+2.webp')`,
  `('Surge Warm Long Sleeve', 'Mens', 98, 12, 'Running and Training', 'Lightweight, Rulu Fabric', 'Relaxed Fit', 'True Navy', 'White', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'Hoodies and Sweatshirt', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Long+Sleeve+Heathered+True+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Long+Sleeve+Heathered+True+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Long+Sleeve+White+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Surge+Warm+Long+Sleeve+White+2.webp')`,
  `('Shift Stitch Full Zip Hoodie', 'Mens', 69, 12, 'On the Move', 'Soft, Stretch French Terry Fabric', 'Classic Fit', 'Black', 'Palm Deco', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Palm+Deco.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Shift+Stitch+Full+Zip+Hoodie+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Shift+Stitch+Full+Zip+Hoodie+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Shift+Stitch+Full+Zip+Hoodie+Palm+Deco+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Shorts/Hoodies/Shift+Stitch+Full+Zip+Hoodie+Palm+Deco.webp')`,
  `('Metal Vent Tech Polo 2.0', 'Mens', 98, 12, 'Training', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit', 'Black', 'Tempest Blue', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Tempest+Blue.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Polo+2.0+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Polo+2.0+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Polo+2.0+Tempest+Blue+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Polo+2.0+Tempest+Blue+2.webp')`,
  `('Evolution Polo', 'Mens', 88, 12, 'Training', 'Sweat-wicking fabric', 'Relaxed Fit', 'Palm Deco', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Palm+Deco.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Polo+Palm+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Polo+Palm+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Polo+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Polo+Navy+2.webp')`,
  `('Tech Pique Polo Updated', 'Mens', 98, 12, 'On the Move', 'Anti-stink fabric', 'Relaxed Fit', ' White', 'Black',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Tech+Pique+Polo+Updated+White+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Tech+Pique+Polo+Updated+White+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Tech+Pique+Polo+Updated+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Tech+Pique+Polo+Updated+Black+2.webp')`,
  `('Evolution Long Sleeve Polo', 'Mens', 88, 12, 'Training', 'A blend of Pima Cotton for optimal softness', 'Relaxed Fit', 'Black', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Long+Sleeve+Polo+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Long+Sleeve+Polo+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Long+Sleeve+Polo+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Evolution+Long+Sleeve+Polo+Navy+2.webp')`,
  `('Metal Vent Tech 1/2 Zip 2.0', 'Mens', 98, 12, 'Training', 'Sweat-wicking fabric', 'Relaxed fit', 'True Navy', 'Sequoia', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Sequoia.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+12+Zip+2.0+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+12+Zip+2.0+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+12+Zip+2.0+Red+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+12+Zip+2.0+Red+2.webp')`,
  `('Metal Vent Tech Long Sleeve 2.0', 'Mens', 88, 12, 'On the Move', 'Super-Soft, VitaSea Fabric', 'Relaxed fit', 'True Navy', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Long+Sleeve+2.0+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Long+Sleeve+2.0+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Long+Sleeve+2.0+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Long+Sleeve+2.0+Black+2.webp')`,
  `('Pulse Motivation Short Sleeve', 'Mens', 78, 12, 'On the Move', 'Sweat-wicking fabric', 'Relaxed Fit', 'Vapor', 'Cadet Blue', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cadet+Blue.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Pulse+Motivation+Short+Sleeve+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Pulse+Motivation+Short+Sleeve+Vapor+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Pulse+Motivation+Short+Sleeve+Cadet+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Pulse+Motivation+Short+Sleeve+Cadet+2.webp')`,
  `('Metal Vent Breathe Short Sleeve', 'Mens', 78, 12, 'On the Move', 'Super-Soft, VitaSea Fabric', 'Relaxed fit', 'Black', 'Incognito Camo Multi Grey', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Short+Sleeve+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Short+Sleeve+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Short+Sleeve+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Short+Sleeve+Camo+2.webp')`,
  `('Metal Vent Breathe Long Sleeve', 'Mens', 88, 12, 'On the Move', 'Super-Soft, VitaSea Fabric', 'Relaxed fit', 'Black', 'Incognito Camo Multi Grey', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Long+Sleeve+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Long+Sleeve+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Long+Sleeve+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Breathe+Long+Sleeve+Camo+2.webp')`,
  `('5 Year Basic Long Sleeve', 'Mens', 88, 12, 'On the Move', 'Super-Soft, VitaSea Fabric', 'Relaxed Fit', 'True Navy', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Black+2.webp')`,
  `('5 Year Basic Tee', 'Mens', 88, 12, 'Training', 'Abrasion-Resistant Fabric', 'Relaxed Fit', 'True Navy', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Tee+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Tee+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Tee+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Tee+Black+2.webp')`,
  `('Metal Vent Tech Sleeveless 2.0', 'Mens', 68, 12, 'Training', 'A blend of Pima Cotton for optimal softness', 'Relaxed Fit', 'Black', 'Tempest Blue', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Tempest+Blue.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Sleeveless+2.0+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Sleeveless+2.0+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Sleeveless+2.0+Tempest+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Sleeveless+2.0+Tempest+2.webp')`,
  `('5 Year Basic Long Sleeve Henley', 'Mens', 68, 12, 'Training', 'Abrasion-Resistant Fabric', 'Relaxed Fit', 'Black', 'Heather Allover Sea Salt Light Cast', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heather+Allover+Iron+Blue+True+Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Henley+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Henley+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Henley+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+Long+Sleeve+Henley+Grey+2.webp')`,
  `('Metal Vent Tech Short Sleeve Henley 2.0', 'Mens', 88, 12, 'Training', 'A blend of Pima Cotton for optimal softness', 'Relaxed Fit', 'Sea Water', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Sea+Water.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Short+Sleeve+Henley+2.0+Sea+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Short+Sleeve+Henley+2.0+Sea+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Short+Sleeve+Henley+2.0+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Short+Sleeve+Henley+2.0+Black+2.webp')`,
  `('Fast and Free Tank', 'Mens', 68, 12, 'Training', 'Abrasion-Resistant Fabric', 'Relaxed Fit', 'Graphite Grey', 'Vapor', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp' ,'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Fast+and+Free+Tank+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Fast+and+Free+Tank+Grey+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Fast+and+Free+Tank+Vapor+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Fast+and+Free+Tank+Vapor+2.webp')`,
  `('5 Year Basic V', 'Mens', 58, 12, 'Training', 'Abrasion-Resistant Fabric', 'Relaxed Fit', 'White', 'Heather Allover Sea Salt Light Cast', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heather+Allover+Iron+Blue+True+Navy.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+V+White+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+V+White+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+V+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Polos/5+Year+Basic+V+Grey+2.webp')`,
  `('Align Crop 21in', 'Womens', 88, 12, 'Yoga', 'Buttery-soft Nulu Fabric', 'High Rise Fit', 'Incognito Camo Multi Grey', 'Chambray',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Chambray.webp', 'Pants','https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Crop+21+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Crop+21+Camo+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Crop+21+Chambray+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Crop+21+Chambray+2.webp')`,
  `('Align Pant II 25in', 'Womens', 98, 12, 'Yoga', 'Buttery-soft Nulu Fabric', 'High Rise Fit', 'Incognito Camo Multi Grey', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Pant+II+25%22+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Pant+II+25%22+Camo+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Pant+II+25%22+Green+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Pant+II+25%22+Green+2.webp')`,
  `('Align Super High-Rise Crop 21in', 'Womens', 88, 12, 'Yoga', 'Buttery-soft Nulu Fabric', 'High Rise Fit', 'Black', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Super+High-Rise+Crop+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Super+High-Rise+Crop+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Super+High-Rise+Crop+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Super+High-Rise+Crop+Navy+2.webp')`,
  `('Wunder Under Crop High-Rise Roll Down Scallop', 'Womens', 88, 12, 'Yoga', 'Full-On Luxtreme Fabric', 'High Rise Fit', 'Black', 'Cassis', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp',  'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+High-Rise+Roll+Down+Scallop+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+High-Rise+Roll+Down+Scallop+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+High-Rise+Roll+Down+Scallop+cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+High-Rise+Roll+Down+Scallop+cassis+2.webp')`,
  `('Wunder Under Crop High-Rise', 'Womens', 88, 12, 'Yoga', 'Full-On Luxtreme FabricWunder Under Crop (High-Rise)', 'High Rise Fit', 'True Navy', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+(High-Rise)+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+(High-Rise)+Navy+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+(High-Rise)+Green+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+(High-Rise)+Green+2.webp')`,
  `('Fast and Free Tight II 25in Non-Reflective Nulux', 'Womens', 128, 12, 'Running', 'Ultra-Lightweight, Nulux Fabric', 'High Rise Fit', 'Graphite Grey', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Tight+II+25%22+Non-Reflective+Nulux+Grey+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Tight+II+25%22+Non-Reflective+Nulux+Grey+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Tight+II+25%22+Non-Reflective+Nulux+Green+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Tight+II+25%22+Non-Reflective+Nulux+Green+2.webp')`,
  `('Fast and Free Crop II 19in Non-Reflective', 'Womens', 118, 12, 'Running', 'Ultra-Lightweight, Nulux Fabric', 'Tight Fit',  'Incognito Camo Multi Grey', 'Cassis', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Crop+II+19%22+Non-Reflective+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Crop+II+19%22+Non-Reflective+Camo+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Crop+II+19%22+Non-Reflective+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Crop+II+19%22+Non-Reflective+Cassis+2.webp')`,
  `('Wunder Train High-Rise Tight 25in', 'Womens', 98, 12, 'Training', 'Sleek Everlux Fabric', 'Mid Rise Fit', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Train+High-Rise+Tight+25%22+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Train+High-Rise+Tight+25%22+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Train+High-Rise+Tight+25%22+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Train+High-Rise+Tight+25%22+Black+2.webp')`,
  `('Speed Up Tight 28in', 'Womens', 88, 12, 'Running', 'Full-On Luxtreme', 'High Rise Fit', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Speed+Up+Tight+28%22+Online+Only+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Speed+Up+Tight+28%22+Online+Only+Cassis+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Speed+Up+Tight+28%22+Online+Only+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Speed+Up+Tight+28%22+Online+Only+Black+2.webp')`,
  `('In Movement Tight 25in Everlux', 'Womens', 108, 12, 'Training', 'Ultra Quick-Drying, Everlux Fabric', 'Tight Fit', 'Black', 'Formation Camo Deep Coal Multi', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Formation+Camo.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/In+Movement+Tight+25%22+Everlux+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/In+Movement+Tight+25%22+Everlux+Black+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/In+Movement+Tight+25%22+Everlux+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/In+Movement+Tight+25%22+Everlux+Camo+2.webp')`,
  `('All The Right Places Crop II 23in', 'Womens', 98, 12, 'Running and Training', 'Full-On Luxtreme', 'High Rise Fit', 'Cassis', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/All+The+Right+Places+Crop+II+23+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/All+The+Right+Places+Crop+II+23+Cassis+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/All+The+Right+Places+Crop+II+23+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/All+The+Right+Places+Crop+II+23+Navy+2.webp')`,
  `('Pace Rival High-Rise Crop', 'Womens', 108, 12, 'Training', 'Ultra Quick-Drying, Everlux Fabric', 'High Rise Fit', 'Dark Olive', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp',  'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Pace+Rival+High-Rise+Crop+Green+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Pace+Rival+High-Rise+Crop+Green+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Pace+Rival+High-Rise+Crop+Navy+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Pace+Rival+High-Rise+Crop+Navy+2.webp')`,
  `('Time To Sweat Crop 23in', 'Womens', 128, 12, 'Running', 'Buttery-soft Nulu Fabric', 'Mid Rise Fit', 'Formation Camo Deep Coal Multi', 'Cassis', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Formation+Camo.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Time+To+Sweat+Crop+23%22+Camo+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Time+To+Sweat+Crop+23%22+Camo+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Time+To+Sweat+Crop+23%22+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Time+To+Sweat+Crop+23%22+Cassis+2.webp')`,
  `('Invigorate High-Rise Crop 23in', 'Womens', 118, 12, 'Running', 'Buttery-soft Nulu Fabric', 'Tight Fit', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Pants', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Invigorate+High-Rise+Crop+23%22+Cassis+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Invigorate+High-Rise+Crop+23%22+Cassis+2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Invigorate+High-Rise+Crop+23%22+Black+1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Invigorate+High-Rise+Crop+23%22+Black+2.webp')`,
  `('Define Jacket', 'Womens', 118, 12, 'Yoga and On the Move', 'Luon Fabric', 'Slim Fit, Hip Length', 'Incognito Camo Multi Grey', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Define+Jacket+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Define+Jacket+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Define+Jacket+N1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Define+Jacket+N2.webp')`,
  `('Hooded Define Jacket', 'Womens', 128, 12, 'Yoga and On the Move', 'Buttery-soft Nulu Fabric', 'Slim Fit, Hip Length', 'Diamond Dye Pitch Grey Graphite Grey', 'Grey Sage', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Diamond+Dye.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Grey+Sage.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Hooded+Define+Jacket+Nulu+D1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Hooded+Define+Jacket+Nulu+D2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Hooded+Define+Jacket+Nulu+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Hooded+Define+Jacket+Nulu+G2.webp')`,
  `('Slip into the Movement Short Jacket', 'Womens', 148, 12, 'On the Move', 'Buttery-soft Nulu Fabric', 'Slim Fit, Hip Length', 'White', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Slip+into+the+Moment+Short+Jacket+W1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Slip+into+the+Moment+Short+Jacket+W2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Slip+into+the+Moment+Short+Jacket+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Slip+into+the+Moment+Short+Jacket+B2.webp')`,
  `('Always Effortless Jacket', 'Womens', 128, 12, 'On the Move', 'Water-repellent, Glyde Fabric', 'Slim Fit, Hip Length', 'Grey Sage', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Grey+Sage.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Always+Effortless+Jacket+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Always+Effortless+Jacket+G2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Always+Effortless+Jacket+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Always+Effortless+Jacket+B2.webp')`,
  `('Serene Travels Wrap', 'Womens', 148, 12, 'On the Move', 'Water-repellent Fabric', 'Slim Fit, Hip Length', 'Slate', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Slate.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Coats and Jackets', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Serene+Travels+Wrap+I1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Serene+Travels+Wrap+I2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Serene+Travels+Wrap+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Serene+Travels+Wrap+B2.webp')`,
  `('Brunch and Back Dress', 'Womens', 148, 12, 'On the Move', 'Ribbed Luxtreme Fabric', 'A/B Cup', 'Chicanti', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Chianti.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Dresses', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Brunch+and+Back+Dress+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Brunch+and+Back+Dress+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Brunch+and+Back+Dress+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Brunch+and+Back+Dress+B2.webp')`,
  `('All Yours Hoodie', 'Womens', 108, 12, 'On the Move', 'Four Way Stretch, Cotton-Blend Fleece Fabric', 'Relaxed Fit, Hip Length', 'Cassis', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Hoodie+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Hoodie+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Hoodie+N1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Hoodie+N2.webp')`,
  `('Retreat Yourself Hoodie', 'Womens', 138, 12, 'On the Move', 'Four Way Stretch Fabric', 'Relaxed Fit, Hip Length', 'Graphite Grey', 'Heathered Allover Sea Salt Light Cast', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heather+Allover+Iron+Blue+True+Navy.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Retreat+Yourself+Hoodie+DG1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Retreat+Yourself+Hoodie+DKsa2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Retreat+Yourself+Hoodie+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Retreat+Yourself+Hoodie+G2.webp')`,
  `('All Yours Cropped Hoodie', 'Womens', 98, 12, 'On the Move', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit, Cropped Length', 'Cadet Blue', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cadet+Blue.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Cropped+Hoodie+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Cropped+Hoodie+B2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Cropped+Hoodie+Black1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/All+Yours+Cropped+Hoodie+Black2.webp')`,
  `('Scuba Crew', 'Womens', 98, 12, 'On the Move', 'Soft, Stretch French Terry Fabric', 'Relaxed Fit, Hip Length', 'Incognito Camo Multi Grey', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Incognito+Camo.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Scuba+Crew+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Scuba+Crew+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Scuba+Crew+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Scuba+Crew+B2.webp')`,
  `('Tuck and Gather Pullover', 'Womens', 98, 12, 'On the Move', 'Soft, Modal French Terry Fabric', 'Relaxed Fit, High-Hip Length', 'Graphite Grey', 'Heathered Mod Stargaze', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heathered+Mod+Stargaze.webp', 'Hoodies and Sweatshirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Tuck+and+Gather+Pullover+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Tuck+and+Gather+Pullover+G2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Tuck+and+Gather+Pullover+other1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Tuck+and+Gather+Pullover+other2.webp')`,
  `('Swiftly Tech Long Sleeve 2.0 Race Length', 'Womens', 78, 12, 'Running and Training', 'Anti-Stink, Seamless Construction', 'Slim Fit, Cropped Length', 'Graphite Grey', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Long+Sleeve+2.0+Race+Length+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Long+Sleeve+2.0+Race+Length+G2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Long+Sleeve+2.0+Race+Length+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Long+Sleeve+2.0+Race+Length+B2.webp')`,
  `('Swiftly Tech Racerback 2.0', 'Womens', 58, 12, 'Running and Training', 'Anti-Stink, Seamless Construction', 'Updated Fit, Hip Length', 'White', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Racerback+2.0+W1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Racerback+2.0+W2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Racerback+2.0+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Swiftly+Tech+Racerback+2.0+B2.webp')`,
  `('Cates Tee', 'Womens', 48, 12, 'On the Move', 'Super-soft, Pima Cotton Fabric', 'Relaxed Fit, Cropped Length', 'White', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cates+Tee+W1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cates+Tee+W2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cates+Tee+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cates+Tee+B2.webp')`,
  `('Love Tee V', 'Womens', 48, 12, 'On the Move', 'Super-soft, Pima Cotton Fabric', 'Classic Fit, Hip Length', 'Heather Allover Sea Salt Light Cast', 'Heathered Mod Stargaze', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heather+Allover+Iron+Blue+True+Navy.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Heathered+Mod+Stargaze.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Love+Tee+V+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Love+Tee+V+G2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Love+Tee+V+S1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Love+Tee+V+S2.webp')`,
  `('Daily Lineup Tank', 'Womens', 58, 12, 'Yoga', 'Smooth, Luxtreme Fabric', 'Tight Fit, Cropped Length', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Daily+Lineup+Tank+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Daily+Lineup+Tank+C2.webp','https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Daily+Lineup+Tank+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Daily+Lineup+Tank+B2.webp')`,
  `('Better Best Long Sleeve', 'Womens', 78, 12, 'On the Move', 'Pima Cotton and Vitasea Fabric', 'Tight Fit, Cropped Length', 'Lunar Rock', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Lunar+Rock.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Better+Best+Long+Sleeve+L1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Better+Best+Long+Sleeve+L2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Better+Best+Long+Sleeve+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Better+Best+Long+Sleeve+B2.webp')`,
  `('Hotty Hot Short II 2.5in', 'Womens', 58, 12, 'Running', 'Lightweight, Swift Fabric', 'Low Rise, 2.5in Inseam', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Hotty+Hot+Short+II+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Hotty+Hot+Short+II+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Hotty+Hot+Short+II+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Hotty+Hot+Short+II+B2.webp')`,
  `('Align Short', 'Womens', 58, 12, 'Yoga', 'Buttery-Soft, Nulu Fabric', 'High Rise', 'Diamond Dye Pitch Grey Graphite Grey', 'True Navy', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Diamond+Dye.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Navy.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Align+Short+D1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Align+Short+D2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Align+Short+N1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Align+Short+N2.webp')`,
  `('Speed Up Short 2.5in', 'Womens', 58, 12, 'Running', 'Lightweight, Swift Fabric', 'Low Rise, 2.5in Inseam', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Speed+Up+Short+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Speed+Up+Short+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Speed+Up+Short+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Speed+Up+Short+B2.webp')`,
  `('On the Fly Short Woven 2.5in', 'Womens', 68, 12, 'On the Move', 'Wrinkle-Free, Travel-Woven Fabric', 'Medium Rise, 2.5in Inseam', 'Cassis', 'Dark Olive', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Olive.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/On+the+Fly+Short+Woven+2.5%22+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/On+the+Fly+Short+Woven+2.5%22+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/On+the+Fly+Short+Woven+2.5%22+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/On+the+Fly+Short+Woven+2.5%22+G2.webp')`,
  `('Choose a Side Short Reversible 3in', 'Womens', 68, 12, 'On the Move', 'Lightweight, Swift Fabric', 'Medium Rise, 3in Inseam', 'White', 'Cadet Blue', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/White.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cadet+Blue.webp',  'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Choose+a+Side+Short+S1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Choose+a+Side+Short+S2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Choose+a+Side+Short+I1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Choose+a+Side+Short+I2.webp')`,
  `('In Movement Short','Womens', 48, 12, 'Training', 'Ultra Quick-Drying, Everlux Fabric', 'High Rise, 2.5in Inseam', 'Dark Adobe', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Adobe.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Shorts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/In+Movement+Short+R1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/In+Movement+Short+R2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/In+Movement+Short+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/In+Movement+Short+B2.webp')`,
  `('Play Off The Pleats Skirt 13in', 'Womens', 68, 12, 'Tennis', 'Lightweight, Swift Fabric', 'Medium Rise, 3.5in Inseam', 'Cassis', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Cassis.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Skirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B2.webp')`,
  `('Morning Match Skirt', 'Womens', 78, 12, 'Tennis', 'Lightweight, Swift Fabric', 'High Rise, 4in Inseam', 'Pink Bliss', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Pink+Bliss.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Skirts', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Morning+Match+Skirt+P1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Morning+Match+Skirt+P2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Morning+Match+Skirt+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Morning+Match+Skirt+B2.webp')`,
  `('Flow Y Bra Nulu','Womens', 48, 12, 'Yoga', 'Buttery-Soft, Nulu Fabric', 'Light Support, B/C Cup', 'Diamond Dye Pitch Grey Graphite Grey', 'Chambray', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Diamond+Dye.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Chambray.webp', 'Sport Bras', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Flow+Y+Bra+Nulu+D1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Flow+Y+Bra+Nulu+D2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Flow+Y+Bra+Nulu+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Flow+Y+Bra+Nulu+C2.webp')`,
  `('Free To Be Serene Bra Long Line', 'Womens', 58, 12, 'Training', 'Smooth, Luxtreme Fabric', 'Light Support, C/D Cup', 'Chicanti', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Chianti.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Sport Bras', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Free+To+Be+Serene+Bra+Long+Line+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Free+To+Be+Serene+Bra+Long+Line+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Free+To+Be+Serene+Bra+Long+Line+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Free+To+Be+Serene+Bra+Long+Line+B2.webp')`,
  `('Energy Bra Long Line', 'Womens', 58, 12, 'Training', 'Smooth, Luxtreme Fabric', 'Medium Support, B/C Cup', 'Black', 'Dark Adobe',  1, 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Dark+Adobe.webp', 'Sport Bras', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Energy+Bra+Long+Line+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Energy+Bra+Long+Line+B2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Energy+Bra+Long+Line+R1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Energy+Bra+Long+Line+R2.webp')`,
  `('Rejuvenate Bra', 'Womens', 58, 12, 'Yoga', 'Buttery-Soft, Nulu Fabric', 'Light Support, A/B Cup', 'Pink Bliss', 'Formation Camo Deep Coal Multi', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Pink+Bliss.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Formation+Camo.webp', 'Sport Bras', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Rejuvenate+Bra+O1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Rejuvenate+Bra+O2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Rejuvenate+Bra+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Rejuvenate+Bra+G2.webp')`,
  `('Well Being Sweater', 'Womens', 128, 12, 'Yoga and On the Move', 'Soft, Boolux Knit Fabric', 'Relaxed Fit', 'Vapor', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp','Sweaters', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Well+Being+Sweater+V1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Well+Being+Sweater+V2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Well+Being+Sweater+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Well+Being+Sweater+B2.webp')`,
  `('Find Your Calm Wrap', 'Womens', 138, 12, 'On the Move', 'Soft, Cotton Fabric', 'Relaxed Fit', 'Graphite Grey', 'Black',  'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Sweaters', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Find+Your+Calm+Wrap+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Find+Your+Calm+Wrap+G2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Find+Your+Calm+Wrap+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Find+Your+Calm+Wrap+B2.webp')`,
  `('Sundown Sweater Wrap', 'Womens', 148, 12, 'On the Move', 'Soft, Cashlu Knit Fabric', 'Relaxed Fit', 'Chicanti', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Chianti.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Sweaters', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Sundown+Sweater+Wrap+C1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Sundown+Sweater+Wrap+C2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Sundown+Sweater+Wrap+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Sundown+Sweater+Wrap+B2.webp')`,
  `('Back to Balance Long Sleeve Sweater', 'Womens', 128, 12, 'On the Move', 'Soft, Cashlu Knit Fabric', 'Relaxed Fit', 'Vapor', 'Grey Sage', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Vapor.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Grey+Sage.webp', 'Sweaters', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Back+to+Balance+Long+Sleeve+Sweater+V1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Back+to+Balance+Long+Sleeve+Sweater+V2.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Back+to+Balance+Long+Sleeve+Sweater+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Back+to+Balance+Long+Sleeve+Sweater+G2.webp')`,
  `('Cozy Calling Turtleneck', 'Womens', 148, 12, 'On the Move', 'Soft, Boolux Knit Fabric', 'Relaxed Fit', 'Graphite Grey', 'Black', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Graphite+Grey.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Icons/Black.webp', 'Sweaters', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cozy+Calling+Turtleneck+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cozy+Calling+Turtleneck+G1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cozy+Calling+Turtleneck+B1.webp', 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Cozy+Calling+Turtleneck+B2.webp')`
];



// const queryDb = (mockData) => {
//   mockData.map((product) => {
//     let queryStr = `INSERT INTO products (name, sex, price, reviews, design, fabric, fit, color1, color2, colorId1, colorId2, type, img1, img2, img3, img4) VALUES ${product}`;
//     db.query(queryStr, (err, results) => {
//       if (err) {
//         console.error(err);
//       } else {
//         console.log('Product seeded!');
//       }
//     });
//   });
// };

// queryDb(data);

const fs = require('fs');
const csvWriter = require('csv-write-stream');
var writer = csvWriter();
var faker = require('faker');
var counter = 0;
let randomProductArr = ['Flxible', 'Tuck', 'Long', 'Woven', '2.5in', 'Sweater', 'Back to Balance', 'Under Crop', 'Motivation Short Sleeve', 'Surge Warm', 'Warp Lite']
let randomSex = ['Mens', 'Womens']
let randomDesign = ['On the Move','Yoga and On the Move','Yoga','Training','Tennis','Running']
let randomFabric = ['Soft Boolux Knit Fabric', 'Soft Cashlu Knit Fabric', 'Soft Cotton Fabric', 'Buttery-Soft Nulu Fabric', 'Smooth Luxtreme Fabric', 'Lightweight Swift Fabric']
let randomFit = ['Relaxed Fit', 'Light Support A/B Cup', 'Medium Support B/C Cup', 'High Rise 4in Inseam', 'High Rise 2.5in Inseam', 'High Rise', 'Low Rise 2.5in Inseam', 'Tight Fit Cropped Length']
let randomColors = ['Black', 'Dark Adobe', 'Vapor', 'Grey Sage', 'Cadet Blue', 'White', 'Cassis', 'Dark Olive', 'True Navy','Lunar Rock','Heathered Mod Stargaze','Graphite Grey']
let randomType = ['Sweaters','Sport Bras','Skirts','Shorts','Shirts','Hoodies and Sweatshirts','Coats and Jackets','Pants','Shirts',]
let randomImg = [
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Train+High-Rise+Tight+25%22+Black+2.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Free+To+Be+Serene+Bra+Long+Line+C1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Crop+II+19%22+Non-Reflective+Cassis+2.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Pant+II+25%22+Camo+1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Wunder+Under+Crop+(High-Rise)+Navy+1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Fast+and+Free+Crop+II+19%22+Non-Reflective+Camo+1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/Pants/Align+Crop+21+Camo+2.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Pulse+Motivation+Short+Sleeve+Vapor+2.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Sleeveless+2.0+Tempest+1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Polos/Metal+Vent+Tech+Long+Sleeve+2.0+Black+2.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Define+Jacket+N1.webp',
  'https://lulupics.s3.us-east-2.amazonaws.com/Womens/hoodies+and+sweatshirts/Always+Effortless+Jacket+B1.webp'
              ]
const writeDataCSV = fs.createWriteStream('data.csv');
writeDataCSV.write('id,name,sex,price,reviews,design,fabric,fit,color1,color2,colorId1,colorId2,type,img1,img2,img3,img4\n');

function writeTenMillionUsers(writer, encoding, callback) {
  let i = 10000000;
  let id = 0;

  function write() {
    let ok = true;
    do {
      i -= 1;
      id += 1;
      name = `${randomProductArr[Math.floor(Math.random() * randomProductArr.length)]} ${randomProductArr[Math.floor(Math.random() * randomProductArr.length)]} ${randomProductArr[Math.floor(Math.random() * randomProductArr.length)]}`;
      sex = randomSex[Math.floor(Math.random() * 1)];
      price = Math.floor( (25.99 + (Math.random() * 50) ) ) + 0.99;
      reviews = Math.floor(Math.random() * 15);
      design = randomDesign[Math.floor(Math.random() * randomDesign.length)];
      fabric = randomFabric[Math.floor(Math.random() * randomFabric.length)];
      fit = randomFit[Math.floor(Math.random() * randomFit.length)];
      color1 = randomColors[Math.floor(Math.random() * randomColors.length)];
      color2 = randomColors[Math.floor(Math.random() * randomColors.length)];
      colorId1 = randomColors[Math.floor(Math.random() * randomColors.length)];
      colorId2 = randomColors[Math.floor(Math.random() * randomColors.length)];
      type = randomType[Math.floor(Math.random() * randomType.length)];
      img1 = randomImg[Math.floor(Math.random() * randomImg.length)]; 
      img2 = randomImg[Math.floor(Math.random() * randomImg.length)];
      img3 = randomImg[Math.floor(Math.random() * randomImg.length)];
      img4 = randomImg[Math.floor(Math.random() * randomImg.length)];
      const data = `${id},${name},${sex},${price},${reviews},${design},${fabric},${fit},${color1},${color2},${colorId1},${colorId2},${type},${img1},${img2},${img3},${img4}\n`;
      if (i === 0) {
        writer.write(data, encoding, callback);
      } else {
        ok = writer.write(data, encoding);
      }
    } while (i > 0 && ok);
    if (i > 0) {
      writer.once('drain', write);
    }
  }
write()
}

writeTenMillionUsers(writeDataCSV, 'utf-8', () => {
  writeDataCSV.end();
});

// async const dataGen = () => {
//   writer.pipe(fs.createWriteStream('data.csv'));
//   for (let i = 0; i < 10000000; i++) {
//     writer.write({
//       id: counter++,
//       name: faker.commerce.productName(),
//       sex: randomSex[Math.round(Math.random() * 1)],
//       price: Math.round( (25.99 + (Math.random() * 50) ) ) + 0.99,
//       reviews: Math.round(Math.random() * 15),
//       design: randomDesign[Math.round(Math.random() * randomDesign.length)],
//       fabric: randomFabric[Math.round(Math.random() * randomFabric.length)],
//       fit: randomFit[Math.round(Math.random() * randomFit.length)],
//       color1: randomColors[Math.round(Math.random() * randomColors.length)],
//       color2: randomColors[Math.round(Math.random() * randomColors.length)],
//       colorId1: randomColors[Math.round(Math.random() * randomColors.length)],
//       colorId2: randomColors[Math.round(Math.random() * randomColors.length)],
//       type: randomType[Math.round(Math.random() * randomType.length)],
//       img1: 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B1.webp', 
//       img2: 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B1.webp',
//       img3: 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B1.webp',
//       img4: 'https://lulupics.s3.us-east-2.amazonaws.com/Womens/shirts/Play+Off+The+Pleats+Skirt+B1.webp',
//     })
//   }

//   await writer.end();
//   await console.log('done with 10mil');
// }

// dataGen();

// const mongoose = require('mongoose');
// const Schema = mongoose.Schema;
// var seeder = require('mongoose-seed');
// require('./schema.js');
// const db = 'mongodb://mongo:27018/SDC';


// let Product = mongoose.model('Product', productSchema); // mongoose product model

// module.exports = Product;




// let scrapeImg = (data) => {
//   let output = []
//   for (let i = 0; i < data.length; i++) {
//     let split = data[i].split(',')
    
//     for (let j = 0; j < split.length; j++) {

//       if (split[j].includes('https://lulupics.s3.us-east-2.amazonaws.com/Womens/')) {
//         output.push(split[j])
//       }
//     }
//   }
//   return output
// }

// let randomImage = scrapeImg(data)

